---
port: 4000
host: localhost
safe: false

exclude: [README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title:       "Workshop on Machine Reading for Question Answering (MRQA)"
keywords:    "workshop, machine reading, question answering, reading comprehension"
description: "The official website for the Workshop on Machine Reading for Question Answering"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"

collections:
  - pages_2021
  - pages_2019
  - pages_2018
  - pages_2019_rc
